# Generated by Django 5.2.17 on 2026-09-30 10:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_rating_average_product_rating_count'),
        ('stores', '0003_store_rating_average_store_rating_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlatformMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(unique=True)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('orders_cancelled', models.PositiveIntegerField(default=0)),
                ('orders_paid', models.PositiveIntegerField(default=0)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('products_sold', models.PositiveIntegerField(default=0)),
                ('active_customers', models.PositiveIntegerField(default=0)),
                ('active_sellers', models.PositiveIntegerField(default=0)),
                ('gmv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('merchandise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('shipping', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('captured_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('refunded_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
            options={
                'verbose_name': 'daily platform metric',
                'verbose_name_plural': 'daily platform metrics',
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='DailyProductMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('merchandise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_metrics', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_product_metrics', to='stores.store')),
            ],
            options={
                'verbose_name': 'daily product metric',
                'verbose_name_plural': 'daily product metrics',
                'ordering': ['-day', 'store_id', 'product_id'],
                'indexes': [models.Index(fields=['product', 'day'], name='reporting_product_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'store', 'product'), name='reporting_product_day_unique')],
            },
        ),
        migrations.CreateModel(
            name='DailyStoreMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('products_sold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text='Received at least one non-cancelled order.')),
                ('merchandise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('shipping', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('promotion_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('voucher_seller_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('seller_funded_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('captured_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('refunded_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_metrics', to='stores.store')),
            ],
            options={
                'verbose_name': 'daily store metric',
                'verbose_name_plural': 'daily store metrics',
                'ordering': ['-day', 'store_id'],
                'indexes': [models.Index(fields=['store', 'day'], name='reporting_store_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'store'), name='reporting_store_day_unique')],
            },
        ),
    ]
