# Generated by Django 5.2.17 on 2026-09-30 11:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystoremetric',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystoremetric',
            name='reviews_rating_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Sum of the day's published review ratings; average = sum/count.", max_digits=10),
        ),
        migrations.AddField(
            model_name='dailystoremetric',
            name='voucher_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='dailystoremetric',
            name='voucher_redemptions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
