# Generated by Django 5.2.17 on 2026-09-30 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_dailystoremetric_reviews_count_and_more'),
        ('stores', '0003_store_rating_average_store_rating_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOperationsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(unique=True)),
                ('orders_open', models.PositiveIntegerField(default=0)),
                ('orders_completed', models.PositiveIntegerField(default=0)),
                ('orders_cancelled', models.PositiveIntegerField(default=0)),
                ('orders_refunded', models.PositiveIntegerField(default=0)),
                ('shipments_created', models.PositiveIntegerField(default=0)),
                ('shipments_delivered', models.PositiveIntegerField(default=0)),
                ('returns_filed', models.PositiveIntegerField(default=0)),
                ('returns_approved', models.PositiveIntegerField(default=0)),
                ('returns_rejected', models.PositiveIntegerField(default=0)),
                ('returns_received', models.PositiveIntegerField(default=0)),
                ('refunds_issued', models.PositiveIntegerField(default=0)),
                ('refunds_settled', models.PositiveIntegerField(default=0)),
                ('requests_filed', models.PositiveIntegerField(default=0)),
                ('conversations_opened', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('disputes_opened', models.PositiveIntegerField(default=0)),
                ('disputes_resolved', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'daily operations metric',
                'verbose_name_plural': 'daily operations metrics',
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='DailyStoreOpsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('shipments_created', models.PositiveIntegerField(default=0)),
                ('shipments_delivered', models.PositiveIntegerField(default=0)),
                ('returns_filed', models.PositiveIntegerField(default=0)),
                ('returns_received', models.PositiveIntegerField(default=0)),
                ('disputes_opened', models.PositiveIntegerField(default=0)),
                ('requests_filed', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_ops_metrics', to='stores.store')),
            ],
            options={
                'verbose_name': 'daily store operations metric',
                'verbose_name_plural': 'daily store operations metrics',
                'ordering': ['-day', 'store_id'],
                'indexes': [models.Index(fields=['store', 'day'], name='reporting_store_ops_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'store'), name='reporting_store_ops_day_unique')],
            },
        ),
    ]
