# Generated by Django 5.2.17 on 2026-09-26 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_rating_average_product_rating_count'),
        ('orders', '0003_orderrequest'),
        ('stores', '0003_store_rating_average_store_rating_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('seller', 'Seller'), ('support', 'Support')], db_index=True, default='seller', max_length=16)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('reported', 'Reported')], db_index=True, default='open', max_length=16)),
                ('customer_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('seller_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('support_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_muted_by_customer', models.BooleanField(default=False)),
                ('is_muted_by_seller', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(help_text='The customer participating in the conversation.', on_delete=django.db.models.deletion.PROTECT, related_name='customer_conversations', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Optional order context.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='orders.order')),
                ('product', models.ForeignKey(blank=True, help_text='Optional product context.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='catalog.product')),
                ('store', models.ForeignKey(blank=True, help_text='The store involved (null for customer-support conversations).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='stores.store')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=64)),
                ('details', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.conversation')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conversation_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('attachment_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_system', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['customer', '-updated_at'], name='messaging_c_custome_519300_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['store', '-updated_at'], name='messaging_c_store_i_297864_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['type', 'status'], name='messaging_c_type_d23139_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationreport',
            index=models.Index(fields=['conversation', '-created_at'], name='messaging_c_convers_eea102_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messaging_m_convers_7bc91b_idx'),
        ),
    ]
