# Generated by Django 5.2.17 on 2026-09-30 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('stores', '0003_store_rating_average_store_rating_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('blocked', models.ForeignKey(help_text='The party being blocked — the store owner, not the store.', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_blocks_made', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, help_text='Store context when the blocked party is a seller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_conversations', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'conversation blocks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', '-created_at'], name='messaging_blocker_idx'), models.Index(fields=['blocked'], name='messaging_blocked_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='messaging_one_block_per_pair'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='messaging_no_self_block')],
            },
        ),
    ]
