# Generated by Django 5.2.17 on 2026-09-26 13:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_name', models.CharField(default='Jeyvro', max_length=60)),
                ('support_email', models.EmailField(default='support@jeyvro.com', max_length=254)),
                ('commission_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform commission taken from each sale (percent).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('default_shipping_flat_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat shipping fee a new store starts with (PHP); sellers may edit their own store afterwards.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('default_free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Free-shipping threshold a new store starts with; null means no threshold.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cod_enabled', models.BooleanField(default=True, help_text='When off, checkout refuses Cash on Delivery entirely.')),
                ('payment_expiry_hours', models.PositiveSmallIntegerField(default=24, help_text='Hours an unpaid online payment may stay open (§6 v1.8).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('default_order_updates_email', models.BooleanField(default=True)),
                ('default_promotions_email', models.BooleanField(default=False)),
                ('default_messaging_email', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Staff member who last changed these settings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'platform settings',
                'verbose_name_plural': 'platform settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('commission_rate_percent__gte', 0), ('commission_rate_percent__lte', 100)), name='platform_commission_rate_bounds'), models.CheckConstraint(condition=models.Q(('default_shipping_flat_fee__gte', 0)), name='platform_shipping_fee_non_negative'), models.CheckConstraint(condition=models.Q(('default_free_shipping_threshold__isnull', True), ('default_free_shipping_threshold__gte', 0), _connector='OR'), name='platform_free_threshold_non_negative'), models.CheckConstraint(condition=models.Q(('payment_expiry_hours__gte', 1), ('payment_expiry_hours__lte', 168)), name='platform_payment_expiry_bounds')],
            },
        ),
    ]
