# Generated by Django 5.2.17 on 2026-09-25 08:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('stores', '0002_store_free_shipping_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='Public identifier, e.g. JV-20260925-8F3K2Q7A (services generate it).', max_length=24, unique=True)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('awaiting_payment', 'Awaiting payment'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='placed', max_length=20)),
                ('ship_to_name', models.CharField(max_length=128)),
                ('ship_to_phone', models.CharField(max_length=32)),
                ('shipping_line1', models.CharField(max_length=256)),
                ('shipping_line2', models.CharField(blank=True, max_length=256)),
                ('shipping_city', models.CharField(max_length=128)),
                ('shipping_province', models.CharField(max_length=128)),
                ('shipping_postal_code', models.CharField(max_length=16)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('savings_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(help_text='Snapshot — the store may be renamed later.', max_length=128)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('awaiting_payment', 'Awaiting payment'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='placed', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_orders', to='stores.store')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_title', models.CharField(help_text='Snapshot of the title at purchase time.', max_length=180)),
                ('product_slug', models.SlugField(help_text='Snapshot — keeps order links stable.', max_length=200)),
                ('variant_name', models.CharField(blank=True, max_length=128)),
                ('sku', models.CharField(max_length=64)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Snapshot of the paid unit price.', max_digits=12)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot for savings display; null when there was no discount.', max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.variant')),
                ('seller_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.sellerorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='orders_user_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='orders_grand_total_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='sellerorder',
            index=models.Index(fields=['store'], name='orders_seller_store_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerorder',
            index=models.Index(fields=['status'], name='orders_seller_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerorder',
            constraint=models.UniqueConstraint(fields=('order', 'store'), name='orders_one_seller_order_per_store'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['seller_order'], name='orders_item_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_item_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='orders_item_quantity_positive'),
        ),
    ]
