# Generated by Django 5.2.17 on 2026-09-25 11:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('awaiting_payment', 'Awaiting payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded')], default='placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerorder',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('awaiting_payment', 'Awaiting payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded')], default='placed', max_length=20),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(db_index=True, help_text='Carrier tracking number (e.g. JVTRK-20260925-...).', max_length=64, unique=True)),
                ('carrier', models.CharField(default='manual', help_text='Carrier code: manual, jtexpress, lbc, ninjavan.', max_length=32)),
                ('carrier_name', models.CharField(default='Standard Delivery', help_text='Display name of the carrier.', max_length=128)),
                ('shipping_method', models.CharField(default='standard', help_text='Standard, Express, Same Day, etc.', max_length=64)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping fee portion assigned to this parcel.', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery failed'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('package_weight_grams', models.PositiveIntegerField(blank=True, help_text='Package weight in grams if recorded.', null=True)),
                ('package_notes', models.TextField(blank=True, help_text='Handling notes or instructions.')),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(max_length=128)),
                ('recipient_phone', models.CharField(max_length=32)),
                ('shipping_address_text', models.TextField()),
                ('seller_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.sellerorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='orders.orderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.shipment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=32)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('occurred_at', models.DateTimeField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='orders.shipment')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['seller_order'], name='shipment_seller_order_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['carrier'], name='shipment_carrier_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipment_tracking_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='shipment_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.UniqueConstraint(fields=('shipment', 'order_item'), name='shipment_one_entry_per_order_item'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['shipment', 'occurred_at'], name='tracking_shipment_time_idx'),
        ),
    ]
