# Generated by Django 5.2.17 on 2026-09-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_alter_sellerorder_status_shipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('return', 'Return'), ('refund', 'Refund'), ('issue', 'Report an issue')], max_length=16)),
                ('reason', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('withdrawn', 'Withdrawn')], default='pending', max_length=16)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='orders.order')),
                ('seller_order', models.ForeignKey(blank=True, help_text='Null = the whole order (all stores).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='orders.sellerorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='orders_req_order_idx'), models.Index(fields=['status'], name='orders_req_status_idx')],
            },
        ),
    ]
