# Generated by Django 5.2.17 on 2026-09-27 08:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher_code',
            field=models.CharField(blank=True, help_text='Applied voucher code snapshot; empty = no voucher.', max_length=32),
        ),
    ]
