# Generated by Django 5.2.17 on 2026-09-27 10:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_discount_total_order_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promotion_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
