# Generated by Django 5.2.17 on 2026-09-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_promotion_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('withdrawn', 'Withdrawn')], default='pending', max_length=16),
        ),
    ]
