# Generated by Django 5.2.17 on 2026-09-30 15:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0002_conversationblock'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('review', 'Review'), ('conversation', 'Conversation')], db_index=True, max_length=16)),
                ('rules', models.JSONField(default=list, help_text='Every rule code that fired, so one row can carry a double hit.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('dismissed', 'Dismissed — content was fine'), ('confirmed', 'Confirmed — content was abuse')], db_index=True, default='open', max_length=16)),
                ('rule_detail', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.MinLengthValidator(0)])),
                ('author', models.ForeignKey(help_text='Who wrote the flagged text — the person staff may act against.', on_delete=django.db.models.deletion.PROTECT, related_name='content_flags_authored', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_flags', to='messaging.conversation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_flags_resolved', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_flags', to='reviews.review')),
            ],
            options={
                'verbose_name_plural': 'content flags',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='moderation_status_idx'), models.Index(fields=['kind', 'status'], name='moderation_kind_status_idx'), models.Index(fields=['author', '-created_at'], name='moderation_author_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('conversation__isnull', True), ('review__isnull', False)), models.Q(('conversation__isnull', False), ('review__isnull', True)), _connector='OR'), name='moderation_flag_exactly_one_subject'), models.UniqueConstraint(condition=models.Q(('review__isnull', False)), fields=('review',), name='moderation_one_flag_per_review'), models.UniqueConstraint(condition=models.Q(('conversation__isnull', False)), fields=('conversation',), name='moderation_one_flag_per_conversation')],
            },
        ),
    ]
