# Generated by Django 5.2.17 on 2026-09-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_average',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average of published review ratings; null = no reviews.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of published reviews.'),
        ),
    ]
