# Generated by Django 5.2.17 on 2026-09-27 08:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_rating_average_product_rating_count'),
        ('orders', '0004_order_discount_total_order_voucher_code'),
        ('stores', '0003_store_rating_average_store_rating_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('seller', 'Seller')], default='platform', max_length=16)),
                ('code', models.CharField(help_text='Customer-facing code, stored uppercase (services normalize).', max_length=32, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], max_length=16)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent (0–100) for percentage vouchers; PHP amount for fixed.', max_digits=12)),
                ('min_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cap for percentage vouchers (maximum discount).', max_digits=12, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total redemptions allowed; null = unlimited.', null=True)),
                ('per_user_limit', models.PositiveIntegerField(blank=True, default=1, help_text='Redemptions per customer; null = unlimited.', null=True)),
                ('first_order_only', models.BooleanField(default=False, help_text='Only customers with no prior orders may redeem.')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('funded_by', models.CharField(choices=[('platform', 'Platform-funded'), ('seller', 'Seller-funded'), ('shared', 'Shared')], default='platform', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, help_text='Required for seller vouchers; null for platform vouchers.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_eligibility', to='catalog.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_eligibility', to='catalog.product')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='promotions.voucher')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_usages', to='orders.order')),
                ('store', models.ForeignKey(blank=True, help_text='The funding store for seller vouchers; null for platform vouchers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_usages', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_usages', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='promotions.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['scope'], name='promo_voucher_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['is_active'], name='promo_voucher_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='voucher_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('min_spend__gte', 0)), name='voucher_min_spend_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('discount_type', 'fixed'), ('value__lte', 100), _connector='OR'), name='voucher_percentage_within_100'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('max_discount__isnull', True), ('max_discount__gte', 0), _connector='OR'), name='voucher_max_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('usage_limit__isnull', True), ('usage_limit__gte', 1), _connector='OR'), name='voucher_usage_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('per_user_limit__isnull', True), ('per_user_limit__gte', 1), _connector='OR'), name='voucher_per_user_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='voucher_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'seller'), ('store__isnull', False)), models.Q(('scope', 'platform'), ('store__isnull', True)), _connector='OR'), name='voucher_scope_matches_store'),
        ),
        migrations.AddConstraint(
            model_name='vouchereligibility',
            constraint=models.CheckConstraint(condition=models.Q(('category__isnull', True), ('product__isnull', True), _negated=True), name='voucher_eligibility_requires_target'),
        ),
        migrations.AddConstraint(
            model_name='vouchereligibility',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('voucher', 'product'), name='voucher_eligibility_unique_product'),
        ),
        migrations.AddConstraint(
            model_name='vouchereligibility',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('voucher', 'category'), name='voucher_eligibility_unique_category'),
        ),
        migrations.AddIndex(
            model_name='voucherusage',
            index=models.Index(fields=['voucher', 'user'], name='promo_usage_voucher_user_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherusage',
            index=models.Index(fields=['order'], name='promo_usage_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucherusage',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gt', 0)), name='voucher_usage_discount_positive'),
        ),
        migrations.AddConstraint(
            model_name='voucherusage',
            constraint=models.UniqueConstraint(fields=('voucher', 'order'), name='voucher_one_usage_per_order'),
        ),
    ]
