# Generated by Django 5.2.17 on 2026-09-27 10:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_rating_average_product_rating_count'),
        ('orders', '0005_order_promotion_discount'),
        ('promotions', '0001_initial'),
        ('stores', '0003_store_rating_average_store_rating_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('seller', 'Seller')], default='platform', max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(blank=True, help_text='Required for seller campaigns; null for platform campaigns.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='stores.store')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('product_discount', 'Product discount'), ('flash_sale', 'Flash sale'), ('free_shipping', 'Free shipping'), ('bundle', 'Bundle discount'), ('buy_x_get_y', 'Buy X get Y')], max_length=24)),
                ('label', models.CharField(help_text='Customer-facing badge text (e.g. "20% off").', max_length=120)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='percentage', max_length=16)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percent (0–100) or PHP amount; ignored for free shipping.', max_digits=12)),
                ('min_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('min_qty', models.PositiveIntegerField(default=1, help_text='Bundle floor: total eligible units in the store required (≥2).')),
                ('buy_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('get_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('buy_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_x_get_y_promotions', to='catalog.product')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='promotions.campaign')),
                ('get_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_promotions', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_targets', to='catalog.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_targets', to='catalog.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rules', to='promotions.promotion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usages', to='orders.order')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='promotions.promotion')),
                ('store', models.ForeignKey(help_text='The store whose lines (or shipping) the discount hit.', on_delete=django.db.models.deletion.PROTECT, related_name='promotion_usages', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'seller'), ('store__isnull', True)), models.Q(('scope', 'platform'), ('store__isnull', False)), _connector='OR', _negated=True), name='campaign_scope_store_required'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('buy_product__isnull', False), ('buy_qty__isnull', False), ('get_product__isnull', False), ('get_qty__isnull', False), ('kind', 'buy_x_get_y')), models.Q(models.Q(('kind', 'buy_x_get_y'), _negated=True), ('buy_product__isnull', True), ('buy_qty__isnull', True), ('get_product__isnull', True), ('get_qty__isnull', True)), _connector='OR'), name='promotion_kind_requires_bxgy_products'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('buy_qty__isnull', True), ('get_qty__isnull', True)), models.Q(('buy_qty__gte', 1), ('get_qty__gte', 1)), _connector='OR'), name='promotion_bxgy_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'free_shipping'), ('value__gt', 0), _connector='OR'), name='promotion_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'free_shipping'), models.Q(('discount_type', 'percentage'), _negated=True), ('value__lte', 100), _connector='OR'), name='promotion_percentage_bounded'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'buy_x_get_y'), _negated=True), ('discount_type', 'percentage'), _connector='OR'), name='promotion_bxgy_percentage_only'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'bundle'), _negated=True), ('min_qty__gte', 2), _connector='OR'), name='promotion_bundle_min_qty'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('min_spend__gte', 0)), name='promotion_min_spend_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='promotiontarget',
            constraint=models.CheckConstraint(condition=models.Q(('category__isnull', True), ('product__isnull', True), _negated=True), name='promotion_target_requires_target'),
        ),
        migrations.AddConstraint(
            model_name='promotiontarget',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('promotion', 'product'), name='promotion_target_unique_product'),
        ),
        migrations.AddConstraint(
            model_name='promotiontarget',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('promotion', 'category'), name='promotion_target_unique_category'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['promotion', 'user'], name='promo_rule_usage_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['order'], name='promo_rule_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotionusage',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gt', 0)), name='promotion_usage_discount_positive'),
        ),
        migrations.AddConstraint(
            model_name='promotionusage',
            constraint=models.UniqueConstraint(fields=('promotion', 'order', 'store'), name='promotion_usage_once_per_store'),
        ),
    ]
