# Generated by Django 5.2.17 on 2026-09-28 13:10

import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderrequest_status'),
        ('promotions', '0002_campaign_promotion_promotiontarget_promotionusage_and_more'),
        ('stores', '0003_store_rating_average_store_rating_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherusage',
            name='platform_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='§16.3: the share of discount_amount the platform absorbs.', max_digits=12),
        ),
        migrations.AddField(
            model_name='voucherusage',
            name='seller_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='§16.3: the share of discount_amount the store absorbs.', max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('funded_by', 'platform'), ('scope', 'seller'), _connector='OR'), name='voucher_funding_requires_store'),
        ),
        migrations.AddConstraint(
            model_name='voucherusage',
            constraint=models.CheckConstraint(condition=models.Q(('platform_amount__gte', 0), ('seller_amount__gte', 0)), name='voucher_usage_funding_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='voucherusage',
            constraint=models.CheckConstraint(condition=models.Q(('platform_amount__exact', django.db.models.expressions.CombinedExpression(models.F('discount_amount'), '-', models.F('seller_amount')))), name='voucher_usage_funding_splits_discount'),
        ),
    ]
