# Generated by Django 5.2.17 on 2026-09-26 14:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_rating_average_product_rating_count'),
        ('orders', '0003_orderrequest'),
        ('stores', '0003_store_rating_average_store_rating_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='1–5 stars; the DB CheckConstraint is the floor.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('flagged', 'Flagged'), ('hidden', 'Hidden')], default='published', max_length=16)),
                ('moderation_reason', models.CharField(blank=True, max_length=255)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('seller_reply', models.TextField(blank=True)),
                ('seller_replied_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='The purchase that proved eligibility (verified buyer, §6).', on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='catalog.product')),
                ('store', models.ForeignKey(help_text='Denormalized owning store — replies and store aggregates read it directly.', on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='stores.store')),
                ('user', models.ForeignKey(help_text='The verified buyer — PROTECT: review history is never orphaned.', on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(help_text='Hosted review photo URL.')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abusive', 'Abusive or harassing'), ('irrelevant', 'Not about this product'), ('other', 'Other')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False, help_text='Staff marks a report resolved once moderated.')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_reports', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'status'], name='reviews_product_status_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['store', 'status'], name='reviews_store_status_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status', 'created_at'], name='reviews_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='reviews_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='reviews_one_per_user_product'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='reviews_rating_bounds'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['review'], name='reviews_report_review_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['resolved'], name='reviews_report_resolved_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewreport',
            constraint=models.UniqueConstraint(fields=('review', 'reporter'), name='reviews_one_report_per_user'),
        ),
    ]
