# Generated by Django 5.2.17 on 2026-09-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='restock',
            field=models.BooleanField(default=True, help_text='True = a settled full refund puts the order lines back on the shelf (a manual staff refund). False = the caller already owns the restock story — the Phase 17 returns flow has moved exactly the returned lines, so the ledger reverses but the catalogue must not double-restock.'),
        ),
    ]
