# Generated by Django 5.2.17 on 2026-09-28 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_refund_restock'),
        ('resolutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='return_case',
            field=models.ForeignKey(blank=True, help_text='The return case that authorised this refund (Phase 17).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='resolutions.returncase'),
        ),
    ]
