# Generated by Django 5.2.17 on 2026-09-24 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('banner_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('return_policy', models.TextField(blank=True)),
                ('shipping_policy', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=16)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(help_text='The seller who owns this store — exactly one per user (§6 v1.2).', on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(max_length=128)),
                ('store_description', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_seller_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_applications', to=settings.AUTH_USER_MODEL)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['slug'], name='stores_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['status'], name='stores_status_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['user'], name='stores_user_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['created_at'], name='stores_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerapplication',
            index=models.Index(fields=['status'], name='stores_app_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerapplication',
            index=models.Index(fields=['user'], name='stores_app_user_idx'),
        ),
    ]
