# Generated by Django 5.2.17 on 2026-09-25 08:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='free_shipping_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: this store ships free when its subtotal reaches this amount (§6 v1.7).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='shipping_flat_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per-store flat shipping fee (PHP) charged once per order from this store (§6 v1.7).', max_digits=12),
        ),
    ]
