# Generated by Django 5.2.17 on 2026-09-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_free_shipping_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rating_average',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average of this store’s published review ratings.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of published reviews across this store.'),
        ),
    ]
