# Generated by Django 5.2.17 on 2026-09-28 11:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_alter_orderrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(help_text='Public identifier, e.g. JVRET-20260928-8F3K2Q7A.', max_length=32, unique=True)),
                ('reason', models.CharField(choices=[('damaged', 'Arrived damaged'), ('defective', 'Defective or faulty'), ('wrong_item', 'Wrong item sent'), ('not_as_described', 'Not as described'), ('missing_parts', 'Missing parts or accessories'), ('changed_mind', 'Changed my mind'), ('other', 'Other reason')], max_length=24)),
                ('note', models.TextField(blank=True, help_text='The customer’s own words.')),
                ('status', models.CharField(choices=[('requested', 'Awaiting seller response'), ('approved', 'Approved — send the items back'), ('rejected', 'Rejected'), ('in_transit', 'Return in transit'), ('received', 'Received — restocked'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded'), ('closed', 'Closed'), ('cancelled', 'Cancelled by customer')], default='requested', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Delivery moment the window was measured from.', null=True)),
                ('window_expires_at', models.DateTimeField(blank=True, help_text='Snapshot of the return deadline.', null=True)),
                ('refund_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Server-computed from order snapshots (§17.2), never client input.', max_digits=12)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.CharField(blank=True, help_text='Seller’s reply, shown to the customer.', max_length=255)),
                ('decision_reason', models.CharField(blank=True, help_text='Why it was approved or rejected.', max_length=255)),
                ('admin_override_at', models.DateTimeField(blank=True, null=True)),
                ('admin_override_reason', models.CharField(blank=True, max_length=255)),
                ('admin_override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_cases_overridden', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_cases', to='orders.order')),
                ('request', models.ForeignKey(blank=True, help_text='The Phase 11 intake row this case resolves, when linked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_cases', to='orders.orderrequest')),
                ('requested_by', models.ForeignKey(help_text='The customer who filed the return.', on_delete=django.db.models.deletion.PROTECT, related_name='return_cases_opened', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_cases_responded', to=settings.AUTH_USER_MODEL)),
                ('seller_order', models.ForeignKey(blank=True, help_text='Null = the whole order (every store slice is returning).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_cases', to='orders.sellerorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('created', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('admin_override', 'Staff decision'), ('shipped', 'Return parcel shipped'), ('received', 'Goods received'), ('restocked', 'Stock restored'), ('refund_issued', 'Refund issued'), ('refunded', 'Refund settled'), ('refund_failed', 'Refund failed'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('note', 'Note')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('actor', models.ForeignKey(blank=True, help_text='Null = system-driven (e.g. an automatic close).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='resolutions.returncase')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('restock', models.BooleanField(default=True, help_text='Whether these units go back on the shelf when received.')),
                ('restocked_at', models.DateTimeField(blank=True, help_text='When stock moved for this line; null = nothing has moved yet.', null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resolutions.returncase')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(db_index=True, help_text='Carrier tracking number for the return leg.', max_length=64, unique=True)),
                ('carrier', models.CharField(default='manual', help_text='Carrier code: manual, jtexpress, lbc, ninjavan.', max_length=32)),
                ('carrier_name', models.CharField(default='Standard Delivery', help_text='Display name of the carrier.', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery failed'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('notes', models.TextField(blank=True, help_text='Handling notes, e.g. bring the original packaging.')),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_shipment', to='resolutions.returncase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='returncase',
            index=models.Index(fields=['order'], name='resolutions_case_order_idx'),
        ),
        migrations.AddIndex(
            model_name='returncase',
            index=models.Index(fields=['status'], name='resolutions_case_status_idx'),
        ),
        migrations.AddIndex(
            model_name='returncase',
            index=models.Index(fields=['requested_by'], name='resolutions_case_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='returncase',
            constraint=models.CheckConstraint(condition=models.Q(('refund_due__gte', 0)), name='resolutions_refund_due_non_negative'),
        ),
        migrations.AddIndex(
            model_name='returnevent',
            index=models.Index(fields=['case', 'created_at'], name='resolutions_event_case_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='resolutions_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.UniqueConstraint(fields=('case', 'order_item'), name='resolutions_one_line_per_case'),
        ),
        migrations.AddIndex(
            model_name='returnshipment',
            index=models.Index(fields=['case'], name='resolutions_ship_case_idx'),
        ),
        migrations.AddIndex(
            model_name='returnshipment',
            index=models.Index(fields=['status'], name='resolutions_ship_status_idx'),
        ),
    ]
