# Generated by Django 5.2.17 on 2026-09-28 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderrequest_status'),
        ('resolutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(help_text='Public identifier, e.g. JVDSP-20260928-8F3K2Q7A.', max_length=32, unique=True)),
                ('reason', models.CharField(choices=[('item_not_received', 'Item never arrived'), ('not_as_described', 'Not as described'), ('damaged_in_transit', 'Arrived damaged'), ('wrong_item', 'Wrong item sent'), ('return_rejected', 'Return rejected or ignored'), ('refund_issue', 'Refund missing or wrong'), ('seller_unresponsive', 'Seller unresponsive'), ('other', 'Other reason')], max_length=24)),
                ('statement', models.TextField(help_text='The buyer’s opening statement (§17.3 customer statement).')),
                ('status', models.CharField(choices=[('open', 'Open — awaiting response'), ('under_review', 'Under staff review'), ('resolved', 'Resolved'), ('cancelled', 'Withdrawn by buyer')], default='open', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('buyer_favor', 'Resolved for the buyer'), ('seller_favor', 'Resolved for the seller')], max_length=20)),
                ('resolution_reason', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='orders.order')),
                ('request', models.ForeignKey(blank=True, help_text='The Phase 11 intake row this dispute resolves, when linked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='orders.orderrequest')),
                ('requested_by', models.ForeignKey(help_text='The buyer who escalated.', on_delete=django.db.models.deletion.PROTECT, related_name='disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('return_case', models.ForeignKey(blank=True, help_text='The return this dispute escalates, when raised against one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='resolutions.returncase')),
                ('seller_order', models.ForeignKey(blank=True, help_text='Null = the whole order (every store slice is in dispute).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='orders.sellerorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('created', 'Dispute opened'), ('statement_added', 'Statement added'), ('evidence_added', 'Evidence added'), ('under_review', 'Staff review started'), ('resolved', 'Dispute resolved'), ('cancelled', 'Withdrawn')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('actor', models.ForeignKey(blank=True, help_text='Null = system-driven.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_events', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='resolutions.dispute')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('staff', 'Staff')], max_length=16)),
                ('url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_evidence', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='resolutions.dispute')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisputeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('staff', 'Staff')], max_length=16)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_statements', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='resolutions.dispute')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['order'], name='resolutions_dispute_order_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status'], name='resolutions_dispute_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['requested_by'], name='resolutions_dispute_user_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeevent',
            index=models.Index(fields=['dispute', 'created_at'], name='resolutions_event_dispute_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeevidence',
            index=models.Index(fields=['dispute', 'created_at'], name='resolutions_evid_dispute_idx'),
        ),
        migrations.AddIndex(
            model_name='disputestatement',
            index=models.Index(fields=['dispute', 'created_at'], name='resolutions_stmt_dispute_idx'),
        ),
    ]
